// Real order/delivery data transcribed from EFLOOR's own procurement
// promo cards (public/img/pro-1.jpg .. pro-12.jpg) — date, client, product
// and quantity as printed on each card. Client names are shown exactly as
// they appear on the source cards (most already abbreviated to initials).
export const PROJECT_CASE_STUDIES = [
  {
    image: "/img/pro-1.jpg",
    client: "PT K.E.T",
    label: "Procurement",
    product: "Lem Vinyl 20 KG",
    quantity: "75 Pcs",
    date: "19 Februari 2022",
  },
  {
    image: "/img/pro-2.jpg",
    client: "PT P.P.J",
    label: "Procurement",
    product: "Lem Vinyl 20 KG",
    quantity: "75 Pcs",
    date: "25 November 2023",
  },
  {
    image: "/img/pro-3.jpg",
    client: "PT S.S",
    label: "Procurement",
    product: "Lem Karpet MAX 20 KG",
    quantity: "19 Pcs",
    date: "14 Januari 2026",
  },
  {
    image: "/img/pro-4.jpg",
    client: "Pk. Aji",
    label: "Procurement",
    product: "Lem Karpet MAX 20 KG",
    quantity: "8 Pcs",
    date: "19 Januari 2026",
  },
  {
    image: "/img/pro-5.jpg",
    client: "Pk. Aji",
    label: "Procurement",
    product: "Lem Karpet 4 KG",
    quantity: "20 Pcs",
    date: "5 Februari 2026",
  },
  {
    image: "/img/pro-6.jpg",
    client: "Pk. Arif",
    label: "Procurement",
    product: "Lem Karpet 4 KG",
    quantity: "10 Pcs",
    date: "5 Februari 2026",
  },
  {
    image: "/img/pro-7.jpg",
    client: "PT S.I.T",
    label: "Procurement",
    product: "Lem Karpet 20 KG",
    quantity: "12 Pcs",
    date: "11 Februari 2026",
  },
  {
    image: "/img/pro-8.jpg",
    client: "PT E.K.I",
    label: "Project Needs",
    product: "Lem Karpet Max 4 KG",
    quantity: "20 Pcs",
    date: "23 Februari 2026",
  },
  {
    image: "/img/pro-9.jpg",
    client: "PT W.J.T",
    label: "Supply Toko",
    product: "Lem Karpet 4 KG",
    quantity: "9 Pcs",
    date: "24 Februari 2026",
  },
  {
    image: "/img/pro-10.jpg",
    client: "PT Raja Plafon",
    label: "Kebutuhan Projek",
    product: "Lem Vinyl 1 KG x 30 pcs, Lem Vinyl 4 KG x 30 pcs",
    quantity: "60 Pcs",
    date: "26 Februari 2026",
  },
  {
    image: "/img/pro-11.jpg",
    client: "PT IKS",
    label: "Projek Pembangunan Interior Pabrik",
    product: "Lem Vinyl 20 KG",
    quantity: "10 Pcs",
    date: "27 Februari 2026",
  },
  {
    image: "/img/pro-12.jpg",
    client: "PT STZ",
    label: "Kebutuhan Logistics",
    product: "Lem Vinyl 20 KG",
    quantity: "5 Pcs",
    date: "3 Maret 2026",
  },
];
